%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/cemalsmac/Documents/Documents – Cemal MacBook Pro/MATLAB/Lab2/laserpred.dat
%
% Auto-generated by MATLAB on 26-Mar-2021 10:30:48

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["e01", "Var2"];
opts.SelectedVariableNames = "e01";
opts.VariableTypes = ["double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var2", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "e01", "TrimNonNumeric", true);
opts = setvaropts(opts, "e01", "ThousandsSeparator", ",");

% Import the data
laserpred = readtable("/Users/cemalsmac/Documents/Documents – Cemal MacBook Pro/MATLAB/Lab2/laserpred.dat", opts);

%% Convert to output type
laserpred = table2array(laserpred);

%% Clear temporary variables
clear opts